import { getToolRequestById } from '@/services/toolsService';
import { PrintToolbar, PrintHeader, InfoRow, InfoGrid } from '../../print-components';

export default async function PrintToolRequestPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const result = await getToolRequestById(id);
  const request = result.success && result.data ? result.data : null;

  if (!request) {
    return <div style={{ padding: '24px', textAlign: 'center' }}><p style={{ color: '#6b7280' }}>Request not found</p></div>;
  }

  const r = request as unknown as Record<string, string>;

  return (
    <div className="print-page">
      <style>{`
        @page { margin: 10mm; size: A4 portrait; }
        body { background: white !important; }
        @media print {
          html, body {
            height: 297mm !important;
            min-height: 297mm !important;
            margin: 0 !important;
            padding: 0 !important;
            background: white !important;
            -webkit-print-color-adjust: exact;
            print-color-adjust: exact;
          }
          .no-print { display: none !important; }
        }
      `}</style>
      <PrintToolbar />
      <div className="print-area" style={{ maxWidth: '600px', margin: '0 auto' }}>
        <PrintHeader subtitle="Tool Request Receipt" />

        <section style={{ marginBottom: '24px' }}>
          <h3 className="section-title">Request Information</h3>
          <InfoGrid>
            <InfoRow label="Request ID" value={`#${(request as any).id?.slice(0, 8) || ''}`} />
            <InfoRow label="Tool" value={request.tool_name || 'N/A'} />
            <InfoRow label="Movement Type" value={request.movement_type === 'incoming' ? 'Incoming' : 'Outgoing'} />
            <InfoRow label="Transaction Type" value={r.transaction_type || '-'} />
            <InfoRow label="Quantity" value={String(request.quantity)} />
            <InfoRow label="Status" value={request.status} />
            <InfoRow label="Location" value={r.location || '-'} />
            {request.notes && <InfoRow label="Notes" value={request.notes} colSpan={2} />}
          </InfoGrid>
        </section>

        {request.movement_type === 'outgoing' && (
          <section style={{ marginBottom: '24px', paddingTop: '16px', borderTop: '1px solid #e5e7eb' }}>
            <h3 className="section-title">Delivery Information</h3>
            <InfoGrid>
              <InfoRow label="Vehicle No" value={r.vehicle_no || '-'} />
              <InfoRow label="Delivered To" value={r.delivered_to || '-'} />
              <InfoRow label="Delivered By" value={r.delivered_by || '-'} />
              <InfoRow label="Received By" value={r.received_by || '-'} />
              <InfoRow label="Received From" value={r.received_from || '-'} />
            </InfoGrid>
          </section>
        )}

        {request.movement_type === 'incoming' && (
          <section style={{ marginBottom: '24px', paddingTop: '16px', borderTop: '1px solid #e5e7eb' }}>
            <h3 className="section-title">Receiving Information</h3>
            <InfoGrid>
              <InfoRow label="Vehicle No" value={r.vehicle_no || '-'} />
              <InfoRow label="Received By" value={r.received_by || '-'} />
              <InfoRow label="Received From" value={r.received_from || '-'} />
              <InfoRow label="Delivered To" value={r.delivered_to || '-'} />
              <InfoRow label="Delivered By" value={r.delivered_by || '-'} />
            </InfoGrid>
          </section>
        )}

        <section style={{ paddingTop: '16px', borderTop: '1px solid #e5e7eb' }}>
          <h3 className="section-title">Approval Timeline</h3>
          <InfoGrid>
            <InfoRow label="Created" value={request.created_at ? new Date(request.created_at).toLocaleDateString('en-GB') : '-'} />
            <InfoRow label="Requested By" value={r.requested_by || 'Unknown'} />
            {r.approved_by && <InfoRow label="Approved By" value={r.approved_by} />}
            {r.approved_at && <InfoRow label="Approved At" value={new Date(r.approved_at).toLocaleDateString('en-GB')} />}
            {request.completed_at && <InfoRow label="Completed At" value={new Date(request.completed_at).toLocaleDateString('en-GB')} />}
          </InfoGrid>
        </section>

        <div className="print-footer" style={{ marginTop: '32px', paddingTop: '16px', borderTop: '1px solid #e5e7eb', textAlign: 'center', fontSize: '12px', color: '#9ca3af' }}>
          <p>Generated by SenExpert Global Energies - SGE System</p>
        </div>
      </div>
    </div>
  );
}
