import { getFinancialRequestById } from '@/services/toolsService';
import { PrintToolbar, PrintHeader, InfoRow, InfoGrid } from '../../print-components';

export default async function PrintFinancialRequestPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const result = await getFinancialRequestById(id);
  const request = result.success && result.data ? result.data : null;

  if (!request) {
    return <div style={{ padding: '24px', textAlign: 'center' }}><p style={{ color: '#6b7280' }}>Request not found</p></div>;
  }

  const r = request as unknown as Record<string, string>;

  return (
    <div className="print-page">
      <style>{`
        @page { margin: 15mm; size: A4 portrait; }
        body { background: white !important; }
        @media print {
          body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
          .no-print { display: none !important; }
        }
      `}</style>
      <PrintToolbar />
      <div className="print-area" style={{ maxWidth: '600px', margin: '0 auto' }}>
        <PrintHeader subtitle="Financial Request Receipt" />

        <section style={{ marginBottom: '24px' }}>
          <h3 className="section-title">Request Information</h3>
          <InfoGrid>
            <InfoRow label="Request ID" value={`#${(request as any).id?.slice(0, 8) || ''}`} />
            <InfoRow label="Title" value={request.title} />
            <InfoRow label="Description" value={request.description} colSpan={2} />
            <InfoRow label="Amount" value={`$${request.amount?.toLocaleString()}`} />
            <InfoRow label="Category" value={request.category} />
            <InfoRow label="Status" value={request.status} />
            {request.notes && <InfoRow label="Notes" value={request.notes} colSpan={2} />}
          </InfoGrid>
        </section>

        <section style={{ paddingTop: '16px', borderTop: '1px solid #e5e7eb' }}>
          <h3 className="section-title">Approval Timeline</h3>
          <InfoGrid>
            <InfoRow label="Created" value={request.created_at ? new Date(request.created_at).toLocaleDateString('en-GB') : '-'} />
            <InfoRow label="Requested By" value={r.requested_by || 'Unknown'} />
            {r.approved_by && <InfoRow label="Approved By" value={r.approved_by} />}
            {r.approved_at && <InfoRow label="Approved At" value={new Date(r.approved_at).toLocaleDateString('en-GB')} />}
          </InfoGrid>
        </section>

        <div className="print-footer" style={{ marginTop: '32px', paddingTop: '16px', borderTop: '1px solid #e5e7eb', textAlign: 'center', fontSize: '12px', color: '#9ca3af' }}>
          <p>Generated by SenExpert Global Energies - SGE System</p>
        </div>
      </div>
    </div>
  );
}
